
CREATE TABLE [dbo].[CT_MICRO_POL_CONTRACT_DOC](
	[DOC_ID] [nvarchar](50) NOT NULL CONSTRAINT [DF_CT_MICRO_POL_CONTRACT_DOC_DOC_ID]  DEFAULT (newid()),
	SEQ INT NOT NULL,
	[APPLICATION_ID] [nvarchar](50) NOT NULL,
	[DOC_CODE] [varchar](30) NOT NULL,
	[DOC_NAME] [varchar](30) NOT NULL,
	[DOC_TYPE] [varchar](20) NOT NULL,
	[DOC_SIZE] [varchar](20) NOT NULL,
	[DOC_PATH] [nvarchar](300) NOT NULL,
	[CREATED_BY] [varchar](30) NOT NULL,
	[CREATED_ON] [datetime] NOT NULL,
	[CREATED_REMARKS] [nvarchar](255) NULL,
	[UPDATED_BY] [varchar](30) NULL,
	[UPDATED_ON] [datetime] NULL,
	[UPDATED_REMARKS] [nvarchar](255) NULL,
	[REVIEWED] [int] NULL,
	[REVIEWED_ON] [datetime] NULL,
	[REVIEWED_BY] [varchar](30) NULL,
	[REVIEWED_REMARK] [nvarchar](255) NULL,
 CONSTRAINT [PK__CT_MICRO__C41D45C214A65FDA] PRIMARY KEY CLUSTERED 
(
	[DOC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO




